In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import pickle
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from imblearn.over_sampling import SMOTE

In [3]:
def split_data(indep_X,dep_Y):
    X_train,X_test,y_train,y_test=train_test_split(indep_X,dep_Y,test_size=0.25,random_state=0,stratify=dep_Y)
    return X_train,X_test,y_train,y_test

In [4]:
def selectkbest(X_train,y_train,X_test,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(X_train,y_train)
    X_train_selected=fit1.transform(X_train)
    X_test_selected=fit1.transform(X_test)
    return X_train_selected,X_test_selected

In [5]:
def scale_data(X_train,X_test):
    sc=StandardScaler()
    X_train=sc.fit_transform(X_train)
    X_test=sc.transform(X_test)
    return X_train,X_test

In [6]:
def counterfeit_prediction(classifier,X_test,y_test):
    y_pred=classifier.predict(X_test)
    cft=confusion_matrix(y_test,y_pred)
    Accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    return classifier,Accuracy,report,X_test,y_test,cft

In [7]:
def logistic(X_train,y_train,X_test,y_test):
    classifier=LogisticRegression(random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cft=counterfeit_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,X_test,y_test,cft

In [8]:
def svm_linear(X_train,y_train,X_test,y_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='linear',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cft=counterfeit_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,X_test,y_test,cft

In [9]:
def svm_NL(X_train,y_train,X_test,y_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='rbf',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cft=counterfeit_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,X_test,y_test,cft

In [10]:
def Navie(X_train,y_train,X_test,y_test):
    from sklearn.naive_bayes import GaussianNB
    classifier=GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cft=counterfeit_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,X_test,y_test,cft

In [11]:
def knn(X_train,y_train,X_test,y_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cft=counterfeit_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,X_test,y_test,cft

In [12]:
def Decision(X_train,y_train,X_test,y_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cft=counterfeit_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,X_test,y_test,cft

In [13]:
def random(X_train,y_train,X_test,y_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cft=counterfeit_prediction(classifier,X_test,y_test)
    return classifier,Accuracy,report,X_test,y_test,cft

In [14]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf):
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):
        dataframe['Logistic'][idex]=acclog[number]
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [15]:
cft_pdt_data = pd.read_csv("counterfeit_products_preprocessed_v2.csv",index_col=None)
cft_pdt_data

,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,spelling_errors,domain_age_days,contact_info_complete,return_policy_clear,...,ip_location_mismatch,is_counterfeit,seller_country,shipping_origin,brand_suspicious,category_Cosmetics,category_Electronics,category_Fashion,category_Luxury Goods,category_Pharmaceuticals
0,277.20,3.500000,890,4,128.00000,21.0,0,1440,0,1,...,0,0,1,6,0,0,0,1,0,0
1,89.18,3.978268,1859,3,224.00000,31.0,4,206,0,0,...,1,1,5,5,0,0,1,0,0,0
2,168.40,2.700000,1096,2,98.00000,10.0,0,1069,1,1,...,0,1,7,1,1,0,0,1,0,0
3,130.98,3.100000,1296,3,255.00000,22.0,0,514,1,1,...,0,0,7,6,0,0,0,0,0,0
4,5.00,2.600000,0,2,20.00000,32.0,5,5,0,0,...,0,1,8,9,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,258.50,4.000000,3075,3,403.72551,21.0,0,770,0,0,...,1,0,8,5,0,0,0,0,0,0
4996,5.00,4.200000,1441,3,310.00000,7.0,0,5,0,0,...,1,0,9,9,0,0,0,0,1,0
4997,153.42,3.500000,2451,2,534.00000,35.0,0,2031,1,1,...,0,1,4,6,1,0,0,0,0,0
4998,136.09,3.600000,1367,4,302.00000,1.0,0,1161,0,1,...,1,1,1,7,1,0,0,0,0,1
4999,29.01,3.700000,1497,1,121.00000,30.0,1,1677,1,1,...,0,1,3,1,0,0,0,0,0,1

In [16]:
indep_X=cft_pdt_data.drop('is_counterfeit',axis=1)
dep_Y=cft_pdt_data['is_counterfeit']

In [17]:
X_train,X_test,y_train,y_test=split_data(indep_X,dep_Y)
smote=SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)
print("Train after SMOTE:", y_train.value_counts().to_dict())
print("Test (untouched):", y_test.value_counts().to_dict())

Train after SMOTE: {1: 2214, 0: 2214}
Test (untouched): {0: 738, 1: 512}

In [18]:
X_train,X_test=selectkbest(X_train,y_train,X_test,10)
X_train,X_test=scale_data(X_train,X_test)
X_train.shape,X_test.shape

((4428, 10), (1250, 10))

In [19]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]


classifier,Accuracy,report,X_test,y_test,cft=logistic(X_train,y_train,X_test,y_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cft=svm_linear(X_train,y_train,X_test,y_test)
accsvml.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cft=svm_NL(X_train,y_train,X_test,y_test)
accsvmnl.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cft=knn(X_train,y_train,X_test,y_test)
accknn.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cft=Navie(X_train,y_train,X_test,y_test)
accnav.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cft=Decision(X_train,y_train,X_test,y_test)
accdes.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cft=random(X_train,y_train,X_test,y_test)
accrf.append(Accuracy)

result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [20]:
#10
result

          Logistic    SVMl   SVMnl     KNN  Navie Decision  Random
ChiSquare   0.7432  0.7464  0.7368  0.6752  0.736   0.6256  0.7216

#### Taking K=10 and creating model with Random Forest as it has the best score of 71%